tunnel: kubernetes-tutorial
credentials-file: /etc/cloudflared/credentials/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
# For more about ingress rules, see
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
ingress:
  - hostname: rails-example.kubernetes-tutorial.mynewsdesk.dev
    service: http://rails-example-web
  - hostname: argocd.kubernetes-tutorial.mynewsdesk.dev
    service: https://argocd-server.argocd.svc
    originRequest:
      noTLSVerify: true
  - hostname: grafana.kubernetes-tutorial.mynewsdesk.dev
    service: http://monitoring-grafana.monitoring.svc
  # This rule matches any traffic which didn't match a previous rule and returns 404:
  - service: http_status:404
